### ISSUE TITLE
Cannot load storage module 'Cloudinary'

### ISSUE THREAD

**Issue by morekoya** [GoGoCarl/paperclip-cloudinary#17]
I get the Cannot load storage module 'Cloudinary' error when trying to use paperclip-cloudinary.I have the cloudinary credentials at config/cloudinary.yml and th flie that holds the cloudinary info is as below
```
class Photo < ApplicationRecord
  belongs_to :user
  has_attached_file :image,
    storage: :cloudinary
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end
```

**Comment by GoGoCarl** [comment]
Hi @morekoya, sorry to hear you are having issues.

From the looks of your code snippet, it appears that you have things set up correctly, though make sure you set the `path` option somewhere, or else you'll likely hit an `InfiniteInterpolationError` somewhere down the line!

Anyway, this error generally means that the gem could not be loaded. Can you confirm:

* You have added the gem to your Gemfile
* You have run `bundle install`
* The gem was successfully installed (is listed in Gemfile.lock)?
* You have restarted your server since adding this gem?

**Comment by morekoya** [comment]
It seems to be working fine now. I guess I did not restart my server. Thank you

**Comment by GoGoCarl** [comment]
You're welcome, happy coding!
