### ISSUE TITLE
flush_deletes & video

### ISSUE THREAD

**Issue by lnxpck** [GoGoCarl/paperclip-cloudinary#5]
Hi !

I still have some problems when attachments are videos.
In fact, the .exists? method return always false because the resource_type is not indicated.

Ex : 

```
irb(main):004:0> Cloudinary::Uploader.exists? "overlay_91b5e610-2a89-0134-7dbc-0242ac110001.webm"
=> false
irb(main):005:0> Cloudinary::Uploader.exists? "overlay_91b5e610-2a89-0134-7dbc-0242ac110001.webm", {:resource_type=>:video}
=> true`
```

So @queued_for_delete is empty and nothing is deleting.

I get arround this issue by adding a method to determine resource_type by using the content_type and add resource_type to Cloudinary::Uploader.destroy command.

```
def resource_type
         unless content_type.nil?
          if content_type.include? "video"
            log("resource_type - video")
            return :video
          else
            log("resource_type - image")
            return :image
          end
        end
      end
```

But is not sufficient because paperclib set content_type to nil in queue_all_for_delete method.
So I had to also modify paperclip class.

Finally it's not really an issue but just some remarks to say video are not correctly manage by this gem (maybe in the roadmap ?).
I'am a new Ruby Developper so I don't have the best way to manage video ;)

**Comment by GoGoCarl** [comment]
Hi @plesaint, thanks for all the feedback above.  Yes, this is a known issue; I missed passing the new `cloudinary_url_options` (which includes the resource type details) in the exists/delete functions, and I hope to quick release (v1.2.1) a fix to patch those issues very soon (in a matter of hours/days).

But yes, you are right, images was the sole focus for the initial release.  But, as I alluded to above, proper support for other resource types (like raw files and videos) is currently active in the pipeline (1.3); This release will also make for less verbose declaration of these different content types and supply sensible, but customizable, defaults.  So, you will be able to specify a `:cloudinary_resource_type` key in the configuration hash instead of having to do it through `:cloudinary_url_options`.

I'll keep you posted on these upcoming releases.

Thanks again for the helpful feedback, this is extremely valuable!

**Comment by GoGoCarl** [comment]
Hi @plesaint, 1.3.0 has been released with proper support for resources other than images.  You can now specify the resource type once in your configuration:

``` ruby
has_attached_file :video,
  :storage => :cloudinary,
  :cloudinary_resource_type => :video
```

And it will use that resource type in all calls (exists, delete, url, etc). So, no need to specify it elsewhere anymore, it should just work as expected.

As always, let me know if you have any issues with this release, I hope it suits you well, and thanks again for your feedback.
