### ISSUE TITLE
Invalid public id

### ISSUE THREAD

**Issue by VivianaGarces** [GoGoCarl/paperclip-cloudinary#7]
Hi, I've just installed this gem, I think it's great but I have a problem.

I try to upload pdfs for my app through an api, I used paperclip on a local server and it worked perfectly but now with Heroku I need to use Cloudinary to handle the storage. My model file looks like this:

```
 has_attached_file :pdf,
                    :storage => :cloudinary,
                    :cloudinary_resource_type => :pdf,
                    :folder => 'adjuntos/pdfs/:id/',
                    :path => 'adjuntos/pdfs/:id/:filename.:extension',
                    :url => '/:class/:id/:filename.:extension'
```

At first I had the Paperclip::Errors::InfiniteInterpolationError but I fixed it adding the path. Now I have the next error:

`[fatal] CloudinaryException (public_id (adjuntos/pdfs/1/EV_IN_123456_CCC_8_#_11111_1.pdf) is invalid):`

I already enabled the 'Auto-create folders' option in my settings but I'm getting the same error. I'm kind of new to this service and I don't know if this is a silly issue or is related to the gem.

Thanks in advance.

**Comment by GoGoCarl** [comment]
Hello @VivianaGarces,

Sorry for the delayed response.  Looking at your public_id of

`adjuntos/pdfs/1/EV_IN_123456_CCC_8_#_11111_1.pdf`

It seems that it is indeed invalid due to the `#` character. From the Cloudinary docs:

> Note that the Public ID format only supports alphanumeric characters, dashes (-), periods (.) and underscores (_)

So, the shortest path to resolving your issue would be to rename this file to something that complies with the constraints above -- so, get rid of the `#`.  This step may be automated in a future release, but that is under review, as there are some specific challenges with doing that (namely, handling colliding filenames).

I hope that helps, but please let me know if you have any more questions or if I can assist further.

Thanks for using the software and reporting this issue!

**Comment by VivianaGarces** [comment]
Thanks a lot, that was the problem. I used those names with paperclip and didn't pay attention to that. I'll have to be more careful with the name conventions.

**Comment by GoGoCarl** [comment]
You're welcome!  I did some further research on this and I may actually forward this information up the chain to the folks at Paperclip.  The `#` character should actually be replaced for you, but it seems this replacement is not being done consistently.  If I find out more information, I'll update this ticket.

Thanks again!

**Comment by qureshius** [comment]
Hi, I did what you guys said above and i am still getting the same error ,
here is the error 
CloudinaryException (public_id (/images/7/Chrysanthemum.jpg) is invalid):
