### ISSUE TITLE
InfiniteInterpolationError

### ISSUE THREAD

**Issue by YuriFontella** [GoGoCarl/paperclip-cloudinary#8]
I already had Paperclip running, what do I need to modify besides the model to work correctly as Cloudinary? I have this error, but I have not changed anything in the controller and the view.

Example of how the controller would look

**Comment by GoGoCarl** [comment]
Hi @YuriFontella, please see issue: https://github.com/GoGoCarl/paperclip-cloudinary/issues/1

It sounds like you need to specify a proper path and url option for your attachment.

**Comment by YuriFontella** [comment]
I had seen issue #1 but had not understood the solution ... Thanks.

**Comment by GoGoCarl** [comment]
You're welcome, glad I could help!

**Comment by vanessasoutoc** [comment]
Hi, i have this problem.   
Paperclip::Errors::InfiniteInterpolationError (Paperclip::Errors::InfiniteInterpolationError):

I not understand this soluction.

**Comment by GoGoCarl** [comment]
@vanessasoutoc Apologies for the delay!

Generally this happens when you do not specify a `path` option when configuration your `has_attached_file` options. See #1 for details: https://github.com/GoGoCarl/paperclip-cloudinary/issues/1

If you are still having problems, please open a new issue and I'll be happy to help as best I can.
